apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - k8s/postgres.yaml
  - k8s/app.yaml
  - k8s/ingress.yaml

images:
  - name: fastapi-app:local
    newName: ghcr.io/oleksandrperian/sre-core-app
    newTag: latest

secretGenerator:
  - name: postgres-secret
    envs:
      - .env